window.HK_SCHOOLS = [
  {id:1,rank:1,zh:"聖保羅男女中學",en:"St. Paul's Co-educational College",d:"中西區",band:"1A",type:"直資",gender:"男女",moi:"EMI",fee:"約 $79,700",note:"歷年 DSE 狀元最多；DSE／IB 雙軌。"},
  {id:2,rank:2,zh:"喀沙書院",en:"La Salle College",d:"九龍城區",band:"1A",type:"資助",gender:"男",moi:"EMI",fee:"免費",note:"傳統男校龍頭；部分年份較少公開完整 DSE 數據。"},
  {id:3,rank:3,zh:"拔萃女書院",en:"Diocesan Girls' School",d:"油尖旺區",band:"1A",type:"直資",gender:"女",moi:"EMI",fee:"約 $40,000",note:"已公布 DSE 英文及整體 5+ 長期居前列。"},
  {id:4,rank:4,zh:"皇仁書院",en:"Queen's College",d:"灣仔區",band:"1A",type:"官立",gender:"男",moi:"EMI",fee:"免費",note:"官校之首，理科傳統強。"},
  {id:5,rank:5,zh:"嘉諾撒聖瑪利書院",en:"St. Mary's Canossian College",d:"油尖旺區",band:"1A",type:"資助",gender:"女",moi:"EMI",fee:"免費",note:"油尖旺傳統女校。"},
  {id:6,rank:6,zh:"瑪利諾修院學校（中學部）",en:"Maryknoll Convent School (Secondary Section)",d:"九龍城區",band:"1A",type:"資助",gender:"女",moi:"EMI",fee:"免費",note:"九龍城女校名校。"},
  {id:7,rank:7,zh:"聖保福學校",en:"St. Paul's Convent School",d:"灣仔區",band:"1A",type:"直資",gender:"女",moi:"EMI",fee:"約 $50,000",note:"灣仔直資女校。"},
  {id:8,rank:8,zh:"拔萃男書院",en:"Diocesan Boys' School",d:"九龍城區",band:"1A",type:"直資",gender:"男",moi:"EMI",fee:"約 $59,860",note:"DSE／IB 雙軌。"},
  {id:9,rank:9,zh:"協恩中學",en:"Heep Yunn School",d:"九龍城區",band:"1A",type:"直資",gender:"女",moi:"EMI",fee:"約 $41,350",note:"已公布 DSE 主科 5+ 長期高位。"},
  {id:10,rank:10,zh:"聖若瑟書院",en:"St. Joseph's College",d:"中西區",band:"1A",type:"資助",gender:"男",moi:"EMI",fee:"免費",note:"中西區傳統男校。"},
  {id:11,rank:11,zh:"香港培正中學",en:"Pui Ching Middle School",d:"九龍城區",band:"1A",type:"資助",gender:"男女",moi:"EMI",fee:"免費",note:"數理傳統強。"},
  {id:12,rank:12,zh:"英華女學校",en:"Ying Wa Girls' School",d:"中西區",band:"1A",type:"資助",gender:"女",moi:"EMI",fee:"免費",note:"中西區傳統女校。"},
  {id:13,rank:13,zh:"聖公會林護紀念中學",en:"S.K.H. Lam Woo Memorial Secondary School",d:"葷青區",band:"1A",type:"資助",gender:"男女",moi:"EMI",fee:"免費",note:"葷青區龍頭。"},
  {id:14,rank:14,zh:"德望學校",en:"Good Hope School",d:"黃大仙區",band:"1A",type:"直資",gender:"女",moi:"EMI",fee:"約 $36,750",note:"黃大仙區龍頭直資女校。"},
  {id:15,rank:15,zh:"香港道教聯合會鄧顯紀念中學",en:"HKTA Tang Hin Memorial Secondary School",d:"北區",band:"1A",type:"資助",gender:"男女",moi:"混合",fee:"免費",note:"北區龍頭；中文及數學 DSE 表現突出。"},
  {id:16,rank:16,zh:"伊利沙伯中學",en:"Queen Elizabeth School",d:"油尖旺區",band:"1A",type:"官立",gender:"男女",moi:"混合",fee:"免費",note:"官立男女校名校。"},
  {id:17,rank:17,zh:"庇理羅士女子中學",en:"Belilios Public School",d:"東區",band:"1A",type:"官立",gender:"女",moi:"EMI",fee:"免費",note:"東區官立女校龍頭。"},
  {id:18,rank:18,zh:"香港華仁書院",en:"Wah Yan College, Hong Kong",d:"灣仔區",band:"1A",type:"資助",gender:"男",moi:"EMI",fee:"免費",note:"港島華仁。"},
  {id:19,rank:18,zh:"英皇書院",en:"King's College",d:"中西區",band:"1A",type:"官立",gender:"男",moi:"EMI",fee:"免費",note:"中西區官立男校。"},
  {id:20,rank:20,zh:"保良局百周年李兆忠紀念中學",en:"PLK Centenary Li Shiu Chung Memorial College",d:"屯門區",band:"1A",type:"資助",gender:"男女",moi:"混合",fee:"免費",note:"屯門區龍頭之一。"},
  {id:21,rank:21,zh:"聖保羅書院",en:"St. Paul's College",d:"中西區",band:"1A",type:"直資",gender:"男",moi:"混合",fee:"約 $44,000",note:"已公布 DSE 英文及數學表現穩健。"},
  {id:22,rank:22,zh:"聖公會曾肇添中學",en:"S.K.H. Tsang Shiu Tim Secondary School",d:"沙田區",band:"1A",type:"資助",gender:"男女",moi:"混合",fee:"免費",note:"沙田區龍頭。"},
  {id:23,rank:23,zh:"聖士提反女子中學",en:"St. Stephen's Girls' College",d:"中西區",band:"1A",type:"資助",gender:"女",moi:"EMI",fee:"免費",note:"中西區傳統女校。"},
  {id:24,rank:24,zh:"港大同學會書院",en:"HKUGA College",d:"南區",band:"1A",type:"直資",gender:"男女",moi:"混合",fee:"直資收費",note:"南區龍頭直資。"},
  {id:25,rank:25,zh:"保良局第一張永慶中學",en:"PLK No.1 W.H. Cheung College",d:"黃大仙區",band:"1A",type:"資助",gender:"男女",moi:"混合",fee:"免費",note:"黃大仙資助龍頭之一。"},
  {id:26,rank:26,zh:"聖馬可中學",en:"St. Mark's School",d:"東區",band:"1A",type:"資助",gender:"男女",moi:"EMI",fee:"免費",note:"東區英中。"},
  {id:27,rank:27,zh:"張祝珊英文中學",en:"Cheung Chuk Shan College",d:"東區",band:"1A",type:"資助",gender:"男女",moi:"EMI",fee:"免費",note:"東區英中。"},
  {id:28,rank:28,zh:"荃灣官立中學",en:"Tsuen Wan Government Secondary School",d:"荃灣區",band:"1A",type:"官立",gender:"男女",moi:"混合",fee:"免費",note:"荃灣區龍頭；數學 DSE 強。"},
  {id:29,rank:29,zh:"保良局董玉娣中學",en:"PLK Tang Yuk Tien College",d:"屯門區",band:"1A",type:"資助",gender:"男女",moi:"混合",fee:"免費",note:"屯門區龍頭之一。"},
  {id:30,rank:30,zh:"瑪利曼中學",en:"Marymount Secondary School",d:"灣仔區",band:"1A",type:"資助",gender:"女",moi:"EMI",fee:"免費",note:"灣仔傳統女校。"},
  {id:90,rank:90,zh:"東涌天主教學校",en:"Tung Chung Catholic School",d:"離島區",band:"2A",type:"資助",gender:"男女",moi:"混合",fee:"免費",note:"東涌一條龍中學部。"},
  {id:91,rank:91,zh:"香港教育工作者聯會黃楚標中學",en:"HKFEW Wong Cho Bau Secondary School",d:"離島區",band:"2A",type:"資助",gender:"男女",moi:"混合",fee:"免費",note:"東涌區熱門資助中學。"},
  {id:92,rank:92,zh:"靈糧堂怡文中學",en:"Ling Liang Church E Wun Secondary School",d:"離島區",band:"2B",type:"資助",gender:"男女",moi:"CMI",fee:"免費",note:"東涌。"},
  {id:93,rank:93,zh:"佛教筏可紀念中學",en:"Buddhist Fat Ho Memorial College",d:"離島區",band:"2C",type:"直資",gender:"男女",moi:"混合",fee:"約 $6,600",note:"大澳直資。"},
  {id:94,rank:94,zh:"香港青年協會李兆基書院",en:"HKFYG Lee Shau Kee College",d:"離島區",band:"1C",type:"直資",gender:"男女",moi:"EMI",fee:"直資收費",note:"馬灣直資。"}
];
window.DISTRICTS = ["中西區","灣仔區","東區","南區","油尖旺區","深水埔區","九龍城區","黃大仙區","觀塘區","荃灣區","屯門區","元朗區","北區","大埔區","沙田區","西貢區","葷青區","離島區"];
